Use SPDX License for source files
flatcar/mantle pull request #263
Opened 2021-12-07 15:48 UTC by dongsupark

Use SPDX License headers for all source files, mainly to become community-friendly and reduce maintenance issues.

See also https://github.com/flatcar-linux/Flatcar/issues/567.

- [x] Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update)

2021-12-07 15:58 UTC, tormath1 commented on CHANGELOG.md
> +- Use SPDX License for source files ([#263](https://github.com/flatcar-linux/mantle/pull/263))
```suggestion
- Use SPDX License identifier for source files ([#263](https://github.com/flatcar-linux/mantle/pull/263))
```

nit-pick

2021-12-07 16:11 UTC, tormath1 approved these changes
LGTM - glad to have a community copyright :)

2021-12-13 18:29 UTC, t-lo requested changes
Let's update this PR so we add SPDX identifier and copyright notice below the original notice. We should leave the original copyright intact.

2025-03-21 09:29 UTC, dongsupark commented
Not needed any more, closing

2025-03-21 09:29 UTC, closed without merging